apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-classifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-classifier
  template:
    metadata:
      labels:
        app: pet-classifier
    spec:
      containers:
      - name: pet-classifier
        image: ${{ secrets.DOCKER_USERNAME }}/pet-classifier:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: docker-hub-secret